# Generated by Django 5.2.6 on 2026-02-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_enrollment_payment_verified_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
